spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/user/**
              filters:
                - StripPrefix=2

            - id: posts-service
              uri: lb://POSTS-SERVICE
              predicates:
                - Path=/api/v1/posts/**
              filters:
                - StripPrefix=2
#                making authentication filter mandatory here
                - name: AuthenticationFilter

            - id: connection-service
              uri: lb://CONNECTION-SERVICE
              predicates:
                - Path=/api/v1/connections/**
              filters:
                - StripPrefix=2
#                making authentication filter mandatory here
                - name: AuthenticationFilter

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# JWT
jwt:
  secretKey: HiThisIsASecretKeyForApiAuthentication2026v1