spring.application.name=connection-service

# SERVER
server.port=8003
server.servlet.context-path=/connections

# DATABASE
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=MyPassword123

# EUREKA CLIENT
eureka.client.service-url.defaultZone=http://localhost:8761/eureka