spring.application.name=user-service

# SERVER
server.port=8001
server.servlet.context-path=/user

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/Connectly-userDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secretKey=HiThisIsASecretKeyForApiAuthentication2026v1

# EUREKA CLIENT
eureka.client.service-url.defaultZone=http://localhost:8761/eureka