spring.application.name=user-service

server.port=8001
server.servlet.context-path=/posts
spring.datasource.url=jdbc:postgresql://localhost:5432/Connectly-postsDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.ddl-auto=update
