spring.application.name=posts-service

# SERVER
server.port=8002
server.servlet.context-path=/posts

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/Connectly-postsDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# EUREKA CLIENT
eureka.client.service-url.defaultZone=http://localhost:8761/eureka