spring.application.name=posts-service

server.port=8002
server.servlet.context-path=/api/v1/posts

spring.datasource.url=jdbc:postgresql://localhost:5432/Connectly-postsDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
